### ISSUE TITLE
I suggest an option to change how the Lysate Cells work.

### ISSUE THREAD

**Issue by Groovesy** [cheeeeeeeeeen/RoR2-ChensMineLimitChanger#10]
Lysate Cells are a new item in the game, from the SotV DLC, that affect engineer to place 1+ extra sentry in the field. As well as increasing the sentry stored as well depending how many stacks of the cells you have.

The Lysate Cell only adds 1 sentry extra in the field, adding to 3. So I was hoping we could change that where from then on, we could place as many as your mod limits in configs. Giving us the ability to place 4 in the field. Or unlimited depending how many fuel cells you acquire to increase the Lysate Cells stack.

I love using this mod, and looking forward for a response.

**Comment by cheeeeeeeeeen** [comment]
I cannot update the mod anymore as I don't know how to mod the game regarding if there's DLC content or not.

I am not active anymore in the modding scene, so someone else should update this mod, or make a replacement mod for this.

If I have the time to study on the new modding ways, then I can update it. But for now, I don't see myself looking at it.

**Comment by cheeeeeeeeeen** [comment]
Good news. I can update this easily!

Expect an update later.

**Comment by cheeeeeeeeeen** [comment]
Feature implemented. Open a new issue if there are bugs. Cheers!
