### ISSUE TITLE
Initial Mine value configuration

### ISSUE THREAD

**Issue by CRB0628** [cheeeeeeeeeen/RoR2-ChensMineLimitChanger#5]
### Is your feature request related to a problem? Please describe.
When I got this mod, I was really excited to be able to place more than 4 mines because that felt underwhelming for a character based around trapping and area denial tactics, but then when I got it, I realized that it violated my rule of not making a character OVERpowered. I want to play a character that is fun and engaging.

### Describe the solution you'd like
I would love for the config to contain an option to set the initial limit for the mine ability's max charges. I don't want to hold 50 mines at once and immediately charge up to that many at the beginning of each stage, but I still want to be able to place a configurable amount of TOTAL mines. I'd LOVE to have only 5 charges and to be able to use backup mags to great effect to get a higher charge limit, but also be able to place 20 or so mines at a single time.

### Describe alternatives you've considered
I can't think of any other feature that would rectify that feeling of Engi either being far too powerful or rather limited in his options. If you had potential to use Engi's mines to greater effect, then maybe it would mean his mobile turrets aren't a complete waste. So to be able to use the mod in the way I've described is kind of an all-or-nothing for me. If it isn't possible or worth doing, that's totally fine and I respect it, but if you could, it would greatly improve my experience while playing Engi.

### Additional context
I appreciate you just reading my request in the first place, it's super cool of you to leave yourself open to feature requests to help people get more out of modded RoR2. Thanks :3

**Comment by cheeeeeeeeeen** [comment]
A good feature.

**Comment by CRB0628** [comment]
Glad you think so!

**Comment by CRB0628** [comment]
With absolutely no intention of trying to rush you or any judgement whatsoever- how goes the progress? I hope my request hasn't caused any problems for you. :3 Best wishes and hopeful patience.

- Some nerd on the internet

**Comment by cheeeeeeeeeen** [comment]
I am not anymore working on modding. However, other people can do this feature. Let me see what I can do on my side.

**Comment by cheeeeeeeeeen** [comment]
@CRB0628 I have implemented this feature. I hope you enjoy the mod!

**Comment by CRB0628** [comment]
As always, you're a god. Thank you very much!

**Comment by cheeeeeeeeeen** [comment]
There's still the issue about the backup mag. I'll fix thisas well. See #6.
