### ISSUE TITLE
More docs, please!

### ISSUE THREAD

**Issue by ryleu** [cheeeeeeeeeen/RoR2-ChensMineLimitChanger#7]
### Is your feature request related to a problem? Please describe.
I can't figure out how to use this mod at all. I know there's a config file somewhere...

### Describe the solution you'd like
Some additional documentation would be great!

### Describe alternatives you've considered
You could also add an in-game menu.

**Comment by cheeeeeeeeeen** [comment]
Hello. Please use R2Modman or Thunderstore Manager. I have forgotten how the manual configs work.

**Comment by ryleu** [comment]
I was having trouble with r2modman because of the distro I'm using. I got those sorted out and it works perfectly. Thanks!
