### ISSUE TITLE
Spider Mine Error

### ISSUE THREAD

**Issue by Pravdala** [cheeeeeeeeeen/RoR2-ChensMineLimitChanger#8]
### The Bug with Stored Spider Mines
When the regular mines are edited in the config file, the changes apply. When you edit the spider mines, the changes to the number stored or deployed on the field are shown in the description. However, the amount of spider mines you can store do not apply and it remains as 4 by default.

I hope you fix it soon. <3

**Comment by cheeeeeeeeeen** [comment]
I'll try to see if i can fix it today.

**Comment by cheeeeeeeeeen** [comment]
@Pravdala I just tested this setting and it is working. Make sure to check all the config options as they are now separated.

If it still does not work, then there is a mod conflict somewhere. For now, I am closing this issue.
