### ISSUE TITLE
limit of Engineer turrets/mines

### ISSUE THREAD

**Issue by limp-crust** [cheeeeeeeeeen/RoR2-ChensMineLimitChanger#9]
I had seen that your mod makes the limit of Engineer's turrets/mines configurable so. I believe i am able be able to change the limit of Engineer's turrets and mines but i cannot find how to.

**Comment by cheeeeeeeeeen** [comment]
I forgot how all this works, but if you use r2modman, you will be able to edit configuration.

Thing is, these are just files. If you can somehow find where the config files are stored, you may edit those directly.

**Comment by limp-crust** [comment]
ok thanks
